# WieldOS release image — runs the prebuilt SvelteKit (adapter-node) server.
# Generated by scripts/package-release.js in the source repo. Do not edit by hand.
FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY build ./build

EXPOSE 3000

CMD ["node", "build"]
